#!/bin/sh

func laratail () {
	tail -n 1000 -f $1 | laracolorlog
}

func laraserve () {
    make serve | laracolorlog
}

func laracolorlog () {
	awk '
	  /DEBUG/ {print "\033[34m" $0 "\033[39m"}
	  /INFO/ {print "\033[37m" $0 "\033[39m"}
	  /WARNING/ {print "\033[33m" $0 "\033[39m"}
	  /ERROR/ {print "\033[31m" $0 "\033[39m"}
	  !/DEBUG|INFO|WARNING|ERROR/ {print "\033[32m" $0 "\033[39m"}
	'
}
